/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTop: typeof import('element-plus/es')['ElTop']
    HeadBar: typeof import('./src/components/headBar.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeArticle: typeof import('./src/components/homeArticle.vue')['default']
    HomeLeftBar: typeof import('./src/components/homeLeftBar.vue')['default']
    HomeRightBar: typeof import('./src/components/homeRightBar.vue')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    LeftBar: typeof import('./src/components/leftBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopSaver: typeof import('./src/components/topSaver.vue')['default']
  }
}
